# Generated by Django 4.1.7 on 2023-03-22 15:38

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('Category', models.CharField(choices=[('Tanks', 'Танки'), ('Hily', 'Хилы'), ('DD', 'ДД'), ('traders', 'Торговцы'), ('Guild Masters', 'Гилдмастеры'), ('Quest Givers', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Tanners', 'Кожевники'), ('Potion Makers', 'Зельевары'), ('Spell Masters', 'Мастера заклинаний')], default='Tanks', max_length=13)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('commentStatus', models.CharField(choices=[('New', 'Новая'), ('Accept', 'Принята'), ('Reject', 'Отклонена')], default='New', max_length=6)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('commentAdvertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.advertisement')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
