# Generated by Django 4.1.7 on 2023-03-22 18:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
